### ISSUE TITLE
load model when test

### ISSUE THREAD

**Issue by wjyfelicity** [tencent-ailab/3m-asr#4]
2022-07-22 02:07:55 UTC -- INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group

2022-07-22 02:07:55 UTC -- INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic__uqeubqu/none_uv4sn3l_/attempt_0/0/error.json

2022-07-22 02:08:37 UTC -- Traceback (most recent call last):

2022-07-22 02:08:37 UTC --   File "bin/recognize.py", line 149, in <module>

2022-07-22 02:08:37 UTC --     main(args)

2022-07-22 02:08:37 UTC --   File "bin/recognize.py", line 69, in main

2022-07-22 02:08:37 UTC --     model.load_state_dict_comm(param_dict)

2022-07-22 02:08:37 UTC --   File "/code/trainer/model/conformer_aed_moe_catEmbed.py", line 73, in load_state_dict_comm

2022-07-22 02:08:37 UTC --     return ConformerMoeEncoder.load_state_dict_comm(self, state_dict)

2022-07-22 02:08:37 UTC --   File "/code/trainer/model/conformer_moe_catEmbed.py", line 277, in load_state_dict_comm

2022-07-22 02:08:37 UTC --     return self.load_state_dict(whole_model_state)

2022-07-22 02:08:37 UTC --   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1406, in load_state_dict

2022-07-22 02:08:37 UTC --     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

2022-07-22 02:08:37 UTC -- RuntimeError: Error(s) in loading state_dict for Net:

2022-07-22 02:08:37 UTC -- 	size mismatch for encoder.blocks.0.feed_forward.router_weights: copying a param with shape torch.Size([1024, 32]) from checkpoint, the shape in current model is torch.Size([1024, 4]).

2022-07-22 02:08:37 UTC -- 	size mismatch for encoder.blocks.0.feed_forward.experts.w_1.weight: copying a param with shape torch.Size([32, 2048, 512]) from checkpoint, the shape in current model is torch.Size([4, 2048, 512]).

2022-07-22 02:08:37 UTC -- 	size mismatch for encoder.blocks.0.feed_forward.experts.w_1.bias: copying a param with shape torch.Size([32, 2048]) from checkpoint, the shape in current model is torch.Size([4, 2048]).

2022-07-22 02:08:37 UTC -- 	size mismatch for encoder.blocks.0.feed_forward.experts.w_2.weight: copying a param with shape torch.Size([32, 512, 2048]) from checkpoint, the shape in current model is torch.Size([4, 512, 2048]).

2022-07-22 02:08:37 UTC -- 	size mismatch for encoder.blocks.0.feed_forward.experts.w_2.bias: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([4, 512]).

2022-07-22 02:08:37 UTC -- 	size mismatch for encoder.blocks.1.feed_forward.router_weights: copying a param with shape torch.Size([1024, 32]) from checkpoint, the shape in current model is torch.Size([1024, 4]).

2022-07-22 02:08:37 UTC -- 	size mismatch for encoder.blocks.1.feed_forward.experts.w_1.weight: copying a param with shape torch.Size([32, 2048, 512]) from checkpoint, the shape in current model is torch.Size([4, 2048, 512]).

2022-07-22 02:08:37 UTC -- 	size mismatch for encoder.blocks.1.feed_forward.experts.w_1.bias: copying a param with shape torch.Size([32, 2048]) from checkpoint, the shape in current model is torch.Size([4, 2048]).

2022-07-22 02:08:37 UTC -- 	size mismatch for encoder.blocks.1.feed_forward.experts.w_2.weight: copying a param with shape torch.Size([32, 512, 2048]) from checkpoint, the shape in current model is torch.Size([4, 512, 2048]).

2022-07-22 02:08:37 UTC -- 	size mismatch for encoder.blocks.1.feed_forward.experts.w_2.bias: copying a param with shape torch.Size([32, 512]) from checkpoint, the shape in current model is torch.Size([4, 512]).

2022-07-22 02:08:37 UTC -- 	size mismatch for encoder.blocks.2.feed_forward.router_weights: copying a param with shape torch.Size([1024, 32]) from checkpoint, the shape in current model is torch.Size([1024, 4]).

**Comment by ododoyo** [comment]
I guess you are using `recognize.py` with 1 GPU, the script will consider that your MoE model has 4 experts since the `num_experts` in `moe_config.yaml` is set to be 4.  The `total_num_experts` equals `num_experts` times `expert_world_size`. If you want to test your 32-experts model with 1 GPU, please set `num_experts` in `moe_config.yaml` to 32.

**Comment by ododoyo** [comment]
I guess you are using `recognize.py` with 1 GPU, in which situation the script will consider that your MoE model has 4 experts since the `num_experts` in `moe_config.yaml` is set to be 4. The `total_num_experts` equals `num_experts` times `expert_world_size`. If you want to test your 32-experts model with 1 GPU, please set `num_experts` in `moe_config.yaml` to 32.

**Comment by wjyfelicity** [comment]
> I guess you are using `recognize.py` with 1 GPU, in which situation the script will consider that your MoE model has 4 experts since the `num_experts` in `moe_config.yaml` is set to be 4. The `total_num_experts` equals `num_experts` times `expert_world_size`. If you want to test your 32-experts model with 1 GPU, please set `num_experts` in `moe_config.yaml` to 32.

You are right, thank you for your reply.
